language: node_js
node_js:
- stable
addons:
  ssh_known_hosts:
  - rey.webhouse.net
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
before_deploy:
- openssl aes-256-cbc -K $encrypted_a1775817836a_key -iv $encrypted_a1775817836a_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  script: bash scripts/service-deploy.sh dev $TRAVIS_BUILD_DIR $SLACK_HOOK
  skip_cleanup: true
  on:
    branch: dev
- provider: script
  script: bash scripts/service-deploy.sh master $TRAVIS_BUILD_DIR $SLACK_HOOK
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    recipients:
    - cb@webhouse.dk
    on_success: never
    on_failure: always
  slack:
    secure: G2v3UGt5KlGWIL2pnTGp5qH7cv8wjIZRmd5AnwDpTvR35jjl9oeMvgbwIdt9G96rkv0pkTlfXuw5dpZQbJ+JMg9BIgmsQjXIkQK4cyXKnawTFkR9MjiNrQCva+jH1x7yWeeblZ+VtwX9mCg1bE/QCt9TjG2KFSDuMSgabtQWGtYjDlXfItblDEPqEr/Rao2bGWgqFj/hne/pW1guxpUzaNij4Z14jd/EN/C61y+bIPRyovpla5v3ReWSPo3dN3fl2VnLuZ5KioDPZ0bwSz/bXYAeWl2iev8M6zzNhjEpfiazv8Ego1PpyJRjk6mFD7kvEkIYnsQXktEBSPil3ysmzBx0Ya8KZWIMYT7dtjSUox2TY6yu8gPlQUYouhfvMAEup60BdhiZP0rSit8oMnxsuIYkGjSP9HZhqjMp78OoAxDCi+6AQMUgqod6drz6Kf5Yxzd0pr92Q0getvbjCWqDekA953aZmLCBV3RCIWtrhz//MIYL+8ERojwNN1vfqBmBdz+VMoYawD3muVKNaRT6xHSXRZw3I/PLAWiQgQI+GuqgznFV6Gk68yvm9zZYigd/z6+3v0qVWX1CgRZL2Ma1fseNeXhfD7GP7CYtm8cG3KTLjKf69HMrwYAXeqRdjySIyTi494DTk5x5XgY3MMBSNLd2oL3HRU+qNzGT+tZKKHg=
